name: "Linux Voice Assistant"
version: "1.0.0"
slug: "lva"
description: "A HA addon version of Linux Voice Assistant"
arch:
  - aarch64
  - amd64
startup: services
init: false
audio: true
host_network: true
map:
  - config:rw
options: 
  name: "LVA"
schema: 
  name: str
